server:
  port: 8080
spring:
  profiles:
    #运行的环境
    active: dev
  application:
    name: chat-room
  datasource:
    url: jdbc:mysql://${chat-room.mysql.ip}:${chat-room.mysql.port}/${chat-room.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${chat-room.mysql.username}
    password: ${chat-room.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: true
  data:
    redis:
      # Redis服务器地址
      host: ${chat-room.redis.host}
      # Redis服务器端口号
      port: ${chat-room.redis.port}
      # 使用的数据库索引，默认是0
      database: 2
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${chat-room.redis.password}
logging:
  level:
    com.zuu:
      debug

wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${chat-room.wx.callback}
    configs:
      - appId: ${chat-room.wx.appId} # 第一个公众号的appid
        secret: ${chat-room.wx.secret} # 公众号的appsecret
        token: ${chat-room.wx.token} # 接口配置里的Token值
        aesKey: ${chat-room.wx.aesKey} # 接口配置里的EncodingAESKey值

#swagger配置信息
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

knife4j:
  enable: true
  setting:
    language: zh_cn

#开启mybatis-plus逻辑删除支持
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值